"""Run ingestion and lab normalization over a whole cohort and report the outcome.

    uv run python scripts/check_normalization.py dev-1000 [--out PATH]

Aggregates only: for each in-scope analyte, how many observations normalized cleanly and why
the rest did not; ingestion issues by type; lab codes that stay unmapped. Deterministic, so
regenerating from the same cohort gives the same file.
"""

import argparse
from collections import Counter, defaultdict
from decimal import Decimal
from pathlib import Path

from medgraph.ingest.fhir import BundleError, read_bundle_file
from medgraph.ingest.files import iter_data_files
from medgraph.normalize.analytes import ANALYTES
from medgraph.normalize.labs import LOINC, LabStatus, normalize_labs
from medgraph.settings import Settings
from profile_cohort import REPO_ROOT, distribution, load_meta, table

STATUSES: tuple[LabStatus, ...] = (
    "ok",
    "implausible",
    "unit_unknown",
    "unit_incompatible",
    "non_numeric",
    "missing_value",
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Report ingestion and normalization outcomes.")
    parser.add_argument(
        "cohort", help="cohort directory, or a name under $MEDGRAPH_DATA_DIR/synthea"
    )
    parser.add_argument("--out", type=Path, help="markdown output path")
    args = parser.parse_args(argv)
    cohort_dir = Path(args.cohort)
    if not cohort_dir.is_dir():
        cohort_dir = Settings().synthea_dir / args.cohort
    meta = load_meta(cohort_dir)

    n_patients = 0
    issues: Counter[tuple[str, str]] = Counter()
    skipped: Counter[str] = Counter()
    statuses: dict[str, Counter[str]] = defaultdict(Counter)  # loinc -> status counts
    units: dict[str, Counter[str]] = defaultdict(Counter)  # loinc -> "unit -> status"
    ok_values: dict[str, list[float]] = defaultdict(list)  # analyte -> canonical values
    implausible: dict[str, list[Decimal]] = defaultdict(list)
    unmapped: Counter[tuple[str, str]] = Counter()
    for path in iter_data_files(cohort_dir / "fhir", "*.json"):
        try:
            record = read_bundle_file(path)
        except BundleError:
            continue
        n_patients += 1
        issues.update((i.code, i.severity) for i in record.issues)
        skipped.update(record.skipped_resources)
        results = normalize_labs(record)
        for result in results:
            statuses[result.loinc][result.status] += 1
            written = (result.original.code or result.original.unit) if result.original else None
            units[result.loinc][f"{written or '(none)'} → {result.status}"] += 1
            if result.status == "ok" and result.value is not None:
                ok_values[result.analyte].append(float(result.value))
            elif result.status == "implausible" and result.value is not None:
                implausible[result.analyte].append(result.value)
        mapped = {r.observation_id for r in results}
        for obs in record.observations:
            code = obs.code.code(LOINC)
            if "laboratory" in obs.categories and obs.id not in mapped and code:
                unmapped[(code, obs.code.label)] += 1

    out = args.out or REPO_ROOT / "docs" / "data" / f"synthea-{meta['cohort']}-normalization.md"
    lines = [
        f"# Normalization check: {meta['cohort']}",
        "",
        "> **Synthetic data.** Aggregates only; generated by `scripts/check_normalization.py` "
        "from the same pipeline the app uses (`ingest.fhir` then `normalize.labs`). Only "
        "results with status `ok` are eligible for rules.",
        "",
        f"Patients read: {n_patients:,}. Ingestion issues: "
        + (", ".join(f"{c} ({s}) {n:,}" for (c, s), n in sorted(issues.items())) or "none")
        + ".",
        "",
        "## In-scope labs by LOINC code",
        "",
        table(
            ["analyte", "LOINC", "method", *STATUSES],
            [
                [a.key, code, method, *[f"{statuses[code][s]:,}" for s in STATUSES]]
                for a in ANALYTES
                for code, method in a.loinc.items()
                if code in statuses
            ],
        ),
        "",
        "Units as written and what became of them:",
        "",
        table(
            ["LOINC", "unit → status (count)"],
            [
                [code, ", ".join(f"{k} ({n:,})" for k, n in counts.most_common())]
                for code, counts in sorted(units.items())
            ],
        ),
        "",
        "## Canonical values of usable results",
        "",
        table(
            ["analyte", "unit", "values", "min / p5 / median / p95 / max"],
            [
                [
                    a.key,
                    a.canonical_unit,
                    f"{len(ok_values[a.key]):,}",
                    distribution(ok_values[a.key]),
                ]
                for a in ANALYTES
                if ok_values[a.key]
            ],
        ),
        "",
        "Values outside the sanity bounds (kept, shown, never used by rules):",
        "",
        table(
            ["analyte", "bounds", "count", "range"],
            [
                [
                    a.key,
                    f"{a.sanity_low}-{a.sanity_high} {a.canonical_unit}",
                    f"{len(implausible[a.key]):,}",
                    f"{min(implausible[a.key]):.3g} to {max(implausible[a.key]):.3g}",
                ]
                for a in ANALYTES
                if implausible[a.key]
            ],
        )
        if implausible
        else "None.",
        "",
        "## Laboratory codes outside the registry (top 15)",
        "",
        table(
            ["LOINC", "display", "observations"],
            [[code, label, f"{n:,}"] for (code, label), n in unmapped.most_common(15)],
        ),
        "",
        "Out-of-scope resource types (not read): "
        + ", ".join(f"{t} {n:,}" for t, n in skipped.most_common())
        + ".",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"{n_patients:,} patients checked; wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
